# Generated by Django 6.1 on 2026-09-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_competition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization_url',
            field=models.URLField(blank=True, help_text='Situs resmi organisasi atau kepanitiaan, mis. https://bem.cs.ui.ac.id/', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_url',
            field=models.URLField(blank=True, help_text='Tautan versi live atau demo proyek yang bisa dicoba.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_url',
            field=models.URLField(blank=True, help_text='Tautan laporan, makalah, atau technical report proyek.', null=True),
        ),
    ]
